[workspace]
members = ["chrs-lib", "chrs-perft", "chrs", "chrs-app"]
default-members = ["chrs"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.test]
opt-level = 3

[profile.dev]
opt-level = 3

[profile.release]
lto = true
